title: My WildCat Studios Portfolio
description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: ""
url: "https://YOURUSERNAME.github.io" # replace YOURUSERNAME with your GitHub username
theme: jekyll-theme-minima # replace minima with your chosen theme from the list
